### ISSUE TITLE
Erro ao executar o cartão Pessoal

### ISSUE THREAD

**Issue by glaucia86** [DanielObara/Meu-cartao-pessoalDanielObara#1]
@DanielObara me explica aqui... qual é o erro que dá no código?

**Comment by DanielObara** [comment]
![image](https://user-images.githubusercontent.com/42970570/52068233-664fb300-2563-11e9-9562-59eaaf3dcc6b.png)

**Comment by DanielObara** [comment]
pedi pro meu amigo instalar no pc dele e deu isso

**Comment by glaucia86** [comment]
mas quando vc executa no seu pc o comando:

```
> npx dev-danielobara
```

acontece isso também?

**Comment by glaucia86** [comment]
![image](https://user-images.githubusercontent.com/1631477/52071144-87b39d80-2569-11e9-9603-fdad58f4049b.png)

**Comment by glaucia86** [comment]
https://www.npmjs.com/package/danielobara-dev

**Comment by glaucia86** [comment]
vc precisa seguir todos os passos na hora de publicar. incluso o comando:

> npm version major

**Comment by glaucia86** [comment]
`#!/usr/bin/env node
// Usado para dizer ao Node.js que se trata de uma ferramenta do CLI

// Declarando os módulos:
const chalk = require('chalk');
const boxen = require('boxen');

// Definindo as opções para o ‘boxen’:
const options = {
  padding: 1,
  margin: 1,
  borderStyle: "round"
};

// Inclusão do Text e mais as definições do ‘chalk’ e cores:
const data = {
  name: chalk.white('             Daniel Obara /'),
  handle: chalk.white('daniel_obara'),
  work: chalk.white('ReactJs Developer'),
  github: chalk.cyan("https://github.com/DanielObara"),
  linkedin: chalk.cyan("https://www.linkedin.com/in/danielobara/"),
  web: chalk.cyan("https://danielobara.wordpress.com/"),
  npx: chalk.white("npx danielobara-dev"),

  labelOpenSource: chalk.rgb(128, 255, 128).bold('Open Source:'),
  labelWork: chalk.rgb(255, 0, 0).bold('      Work:'),
  labelGitHub: chalk.rgb(253, 245, 5).bold('    GitHub:'),
  labelLinkedIn: chalk.rgb(0, 255, 255).bold('  LinkedIn:'),
  labelWeb: chalk.rgb(255, 136, 77).bold('       Web:'),
  labelCard: chalk.rgb(240, 13, 240).bold('      Card:'),
};

// Aqui será a saída do nosso Cartão Pessoal em NPX:
const newline = '\n';
const heading = `${data.name} ${data.handle}`;
const working = `${data.labelWork}  ${data.work}`;
const githubing = `${data.labelGitHub}  ${data.github}`;
const linkedining = `${data.labelLinkedIn}  ${data.linkedin}`;
const webing = `${data.labelWeb}  ${data.web}`;
const carding = `${data.labelCard}  ${data.npx}`;

// Aqui devemos colocar toda a nossa saída numa única variável para que possamos usar
// o ‘boxen de maneira efetiva:
const output = heading
                + newline
                + newline
                + working
                + newline
                + githubing
                + newline
                + linkedining
                + newline
                + newline
                + webing
                + newline
                + newline
                + carding;

console.log(chalk.green(boxen(output, options)));`

**Comment by glaucia86** [comment]
`{
  "name": "danielobara-dev",
  "version": "3.0.0",
  "description": "",
  "main": "index.js",
  "bin": {
    "danielobara-dev": "./bin/card.js"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "Tierney Cyren, Glaucia Lemos <glaucia_lemos86@hotmail.com> (code4coders.wordpress.com/)",
  "bugs": {
    "url": ""
  },
  "homepage": "",
  "license": "MIT",
  "dependencies": {
    "boxen": "^2.1.0",
    "chalk": "^2.4.1",
    "commander": "^2.19.0"
  },
  "devDependencies": {
    "standard": "^12.0.1"
  }
}
`

**Comment by glaucia86** [comment]
@DanielObara vou deletar do meu npm o teu pacote. copie e cole esses códigos e siga estritamente esses passos:

4. Execute o comando abaixo para que possamos verificar a versão que possuem do **npm**:

```
> npm version major
```

5. Após verificar qual a versão do **npm** que possuem, execute o comando abaixo:

```
> npm adduser
```

6. Enfim, vamos publicar o nosso pacote para o site do npmjs. Para isso, basta executar o seguinte comando abaixo:

```
> npm publish
```

7. E finalmente... execute o comando abaixo para visualizar o seu cartão pessoal criado:

```
> npx glaucia_lemos86 
```

**Comment by DanielObara** [comment]
beleza, eu já deu un unpublish no npm e vou refazer estes passos

**Comment by DanielObara** [comment]
certo, mas esse package.json que voce  postou ali em cima é pra copiar igual?

**Comment by glaucia86** [comment]
sim. Muda o nome de dev-danielobara

**Comment by DanielObara** [comment]
Belesma ;D

**Comment by DanielObara** [comment]
Aeee @glaucia86 deu certo!!! muito obrigadoo!! Tinha tentado a primeira vez desde quando vc postou ai não tinha dado certo... fui tentar de novo agora e agora com a sua ajuda rolou ;D

![captura de tela de 2019-01-31 15-34-18](https://user-images.githubusercontent.com/42970570/52073085-c3e8fd00-256d-11e9-8436-b289663882bb.png)
